export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";
export const AUTH_LOGIN_LOADING = "AUTH_LOGIN_LOADIGN";
export const AUTH_LOGIN_FAIL = "AUTH_LOGIN_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";